services:
  windows:
    image: windows-local:latest
    container_name: windows
    environment:
      VERSION: "win11e"
      STORAGE: "${STORAGE:?Error: required env var not set}"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
      - ${STORAGE}:/storage

  prepare-golden-image:
    extends:
      service: windows
    profiles:
      - prepare-golden-image
    environment:
      ISO: "${ISO:?Error: required env var not set}"
    volumes:
      - ${ISO}:/custom.iso
      - ${STORAGE}:/storage
